// Shared crossword data shape. Puzzles are generated by the backend (see
// infra/lambda/crossword.ts) and fetched via client.ts — the frontend no
// longer generates or bundles puzzles.

// react-crossword's input shape.
export interface CrosswordCell {
  clue: string;
  answer: string;
  row: number; // 0-based
  col: number; // 0-based
}

export interface CrosswordData {
  across: Record<number, CrosswordCell>;
  down: Record<number, CrosswordCell>;
}
